#!/usr/bin/env sh
case "$1" in
  start)
    start-stop-daemon -S -n aesdsocket  /usr/bin/aesdsocket -d
    ;;
  stop)
    start-stop-daemon -K -n  aesdsocket
    ;;
  *)
    echo "aesdsocket error argument"
    exit 1
esac